feat: status 값까지 비교하여 find 할 수 있도록 수정
iamport/iamport-rest-client-python pull request #55
Opened 2022-09-16 08:54 UTC by moonseoklee

- https://api.iamport.kr/#!/payments/getPaymentByMerchantUid 의 status parameter 대응

### 작업 개요

### 작업 분류

### 작업 상세 내용

2022-09-26 18:24 UTC, perhapsspy commented on iamport/client.py
> +        print(url)
print 문은 삭제 부탁드립니다.

2022-09-26 18:27 UTC, perhapsspy requested changes

2022-09-26 18:27 UTC, perhapsspy commented on iamport/client.py
> +            self.imp_url, merchant_uid, status)
한줄로 하려다가 애매한 지점에서 줄바꿈이 되는 것으로 보입니다. 가장 뒤쪽의 '/{}' 부분만 첨가하는 형태로 코드를 만들어 보시는것을 권합니다.

2022-09-26 18:27 UTC, perhapsspy commented on tests/test_find_with_status.py
> +    assert res['merchant_uid'] == '1234qwer'
payload를 위에서 따로 변수 지정하여 분리하지 않고, 각 매게변수에 직접 넣는 것이 더 간단해보입니다.

2022-09-27 04:59 UTC, moonseoklee commented
@perhapsspy 리뷰감사드립니다. 반영하여 커밋하였습니다

2022-09-28 12:20 UTC, perhapsspy approved these changes

2022-09-29 05:06 UTC, perhapsspy commented
@moonseoklee 테스트에서 깨지는 부분 해결 부탁드립니다.

2022-09-29 05:51 UTC, moonseoklee commented
@perhapsspy 라인 컨벤션 수정하였습니다

2022-09-29 11:12 UTC, merged

2022-09-29 11:13 UTC, perhapsspy commented
> @perhapsspy 라인 컨벤션 수정하였습니다

수고하셨습니다.